chore: remove ipython as dev dependency
SwissDataScienceCenter/amalthea pull request #142
Opened 2022-02-16 12:47 UTC by ableuler

ipython has a vulnerability and should not really be there as dev dependency in my opinion.

2022-02-16 16:23 UTC, olevski requested changes
Sounds good - I have no clue why or how we even got it in the first place.

Just the linting is failing. After that will approve.

2022-02-16 17:04 UTC, ableuler commented
> Sounds good - I have no clue why or how we even got it in the first place.

was probably me putting it there on the initial commit per accident.

2022-02-16 18:12 UTC, ableuler commented
hmmm, interesting. Uninstalling ipython downgraded pylint from a pre-release version to the latest released version... Anyway, I've now pinned pylint to the pre-release again, let's hope this fixes things.

2022-02-17 08:26 UTC, olevski approved these changes

2022-02-17 09:14 UTC, merged