feat: specify secret adoption for every secret
SwissDataScienceCenter/amalthea pull request #714
Opened 2024-09-01 19:26 UTC by olevski

2024-09-01 19:26 UTC, olevski commented
This change is part of the following stack:

- #704
    - #714 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

2024-09-27 15:00 UTC, sgaist requested changes

2024-10-02 08:27 UTC, sgaist approved these changes

2024-10-02 08:27 UTC, sgaist commented on api/v1alpha1/amaltheasession_types.go
> +	return s != nil && s.Name != "" && s.Adopt
I did not expect that to be a possible implementation.

Thanks for the trick !

2024-10-02 08:45 UTC, merged